---
env:
  global:
    - USER=loganmarchione
    - REPO=docker-speedtest-influxdb
    - VERSION=$(cat VERSION)

services:
  - docker

jobs:
  include:
    - stage: Build

      script:
        # Build the container
        - docker build --file Dockerfile --tag ${USER}/${REPO}:${VERSION} .

      before_deploy:
        # Login to DockerHub
        - echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER" --password-stdin
        # Image with numbered tag
        - docker tag ${USER}/${REPO}:${VERSION} ${USER}/${REPO}:${VERSION}
        # Image with latest tag
        - docker tag ${USER}/${REPO}:${VERSION} ${USER}/${REPO}:latest

      deploy:
        provider: script
        script: docker push ${USER}/${REPO}:${VERSION} && docker push ${USER}/${REPO}:latest
        on:
          tags: true

      after_deploy:
        # Logout
        - docker logout
